project:
  type: website
  output-dir: docs

website:
  title: "My First Quarto Site"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: darkly
    css: styles.css      # Only include if you have a custom CSS file
    toc: true

editor: visual

